services:
  frontend:
    build:
      context: ./FrontIntranet
    container_name: vite-frontend
    ports:
      - "${LOCAL_FRONT_PORT_ENV}:${DOCKER_FRONT_PORT_ENV}"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_API_URL=${URL_DESARROLLO_ENV}
    command: >
      /bin/bash -c "/usr/local/bin/wait-for-it.sh backend:3000 -- npm run dev"
    volumes:
      - ./FrontIntranet:/app
      - /app/node_modules
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
volumes:
  frontend_volume:
